apps/dailyreport/urls.py
from django.urls import path
from . import views


app_name = 'dailyreport'
urlpatterns = [
    path('', views.MyReportView.as_view(), name='dailyreport'),
    # path('dailyreport/', views.MyCalendarView.as_view(), name='dailyreport'),
    # path('dailyreport/list/', views.EventListView.as_view(), name='dailyreport-list'),
    # path('dailyreport/create/', views.EventCreateView.as_view(), name='dailyreport-create'),

]

apps/mydesk/urls.py
from django.urls import path
from . import views


app_name = 'mydesk'
urlpatterns = [
    path('', views.MyDeskView.as_view(), name='mydesk'),
    path('dailyreport/', views.MyReportView.as_view(), name='dailyreport'),
    path('dailyreport/create/', views.EventCreateView.as_view(), name='dailyreport-create'),
    path('dailyreport/json/', views.EventListView.as_view(), name='dailyreport-json'),
    path('dailyreport/detail/', views.EventDetailView.as_view(), name='dailyreport-detail'),
    path('dailyreport/test/', views.TestView.as_view(), name='dailyreport-test'),

]

zbd_site/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from system.views_user import IndexView, LoginView, LogoutView
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('system/', include('system.urls', namespace='system')),
    path('sometools/', include('sometools.urls', namespace='sometools')),
    path('mydesk/', include('mydesk.urls', namespace='mydesk')),

]

if settings.DEBUG:  # 在测试环境中处理图片资源的方式
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

apps/mydesk/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone


User = get_user_model()  # 取用户模型


class EventType(models.Model):
    """
    事件类型，记录事件类型的字典，包括事件的颜色，为后期显示和统计使用
    """
    name = models.CharField(max_length=20, verbose_name='事件类型')
    color = models.CharField(max_length=10, verbose_name='表示颜色')

    class Meta:
        verbose_name = '事件类型'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class DailyReport(models.Model):
    """
    事件日历
    """
    title = models.TextField(max_length=1000, verbose_name="日程")
    type = models.ForeignKey('EventType', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='日程类型')
    start = models.DateTimeField(null=True, blank=True, verbose_name='开始时间')
    end = models.DateTimeField(null=True, blank=True, verbose_name='结束时间')
    allday = models.BooleanField(default=False, verbose_name='全天')
    user = models.ForeignKey(User, related_name='report_user', on_delete=models.DO_NOTHING, default='')
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    addtime = models.DateTimeField(default=timezone.now, verbose_name='创建时间')

    class Meta:
        ordering = ['start', '-end']
        verbose_name = "日历日程"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

apps/mydesk/forms.py
from django import forms
from .models import DailyReport


class EventCreateForm(forms.ModelForm):
    title = forms.CharField(
        required=True,
        min_length=2,
        max_length=1000,
        error_messages={
            'required': '日程不能为空',
            'min_length': '日程长度最小2个字符',
            'max_length': '日程长度不能超过1000个字符',
        }
    )

    class Meta:
        model = DailyReport
        fields = ['title', 'type', 'start', 'end', 'allday', 'participants', 'user']
        error_messages = {
            'start': {'required': '开始时间不能为空'},

        }

    def clean(self):
        cleaned_data = super(EventCreateForm, self).clean()
        start_time = cleaned_data.get('start')
        end_time = cleaned_data.get('end')
        if end_time < start_time:
            raise forms.ValidationError('结束时间应不小于开始时间！')

apps/mydesk/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View, TemplateView
from system.mixin import LoginRequiredMixin
from django.http import JsonResponse
from .models import EventType, DailyReport
from .forms import EventCreateForm
from django.contrib.auth import get_user_model
from django.db.models import Q
import datetime
import re


User = get_user_model()


class TestView(LoginRequiredMixin, TemplateView):

    template_name = 'mydesk/dailyreport/test.html'


class MyDeskView(LoginRequiredMixin, TemplateView):

    template_name = 'mydesk/index.html'


class MyReportView(LoginRequiredMixin, TemplateView):

    template_name = 'mydesk/dailyreport/myreport.html'


class EventCreateView(LoginRequiredMixin, View):

    def get(self, request):
        start = end = None
        if 'start' in request.GET and request.GET['start']:
            start = request.GET['start']
            start = ' '.join(start.split('T'))  # 目的是为了将'YYYY-MM-DDThh:mm'转换为'YYYY-MM-DD hh:mm'
        if 'end' in request.GET and request.GET['end']:
            end = request.GET['end']
            end = ' '.join(end.split('T'))  # 同start
        ret = {
            'participants': User.objects.exclude(username__in=['admin', ]),  # 暂时不考虑不是一个部门的人员
            'types': EventType.objects.all(),
            'start': start,
            'end': end
        }
        return render(request, 'mydesk/dailyreport/report_create.html', ret)

    def post(self, request):
        event_create_form = EventCreateForm(request.POST)
        if event_create_form.is_valid():
            event_create_form.save()  # 提交
            ret = {'result': True}
        else:
            pattern = '<li>.*?<ul class=.*?><li>(.*?)</li>'
            errors = str(event_create_form.errors)
            event_create_form_errors = re.findall(pattern, errors)
            ret = {
                'result': False,
                'event_create_form_errors': event_create_form_errors[0]
            }
        return JsonResponse(ret)


class EventListView(LoginRequiredMixin, View):

    def post(self, request):
        # get方法取得日历事件
        fields = ['id', 'type', 'title', 'start', 'end', 'allday', 'type__color']
        start = end = None
        if 'start' in request.POST and request.POST['start']:
            start = datetime.datetime.strptime(request.POST['start'], '%Y-%m-%dT%H:%M:%S')
        if 'end' in request.POST and request.POST['end']:
            end = datetime.datetime.strptime(request.POST['end'], '%Y-%m-%dT%H:%M:%S')
        if start and end:
            qs = DailyReport.objects.filter(start__gte=start).filter(end__lte=end).values(*fields)
        elif start:
            qs = DailyReport.objects.filter(start__gte=start).values(*fields)
        elif end:
            qs = DailyReport.objects.filter(end__lte=end).values(*fields)
        else:
            qs = DailyReport.objects.values(*fields)
        ret = dict(data=list(qs))  # 传一个列表，用于取得想要的字段
        return JsonResponse(ret)


class EventDetailView(LoginRequiredMixin, View):
    """
    日程详情:用于展示日程或者修改、删除日程
    """
    def get(self, request):
        ret = dict()
        if 'id' in request.GET and request.GET['id']:
            report = get_object_or_404(DailyReport, pk=int(request.GET['id']))
            ret = {
                'report': report,
                'user_all': User.objects.exclude(username__in=['admin', ]),
                'types': EventType.objects.all(),
            }
        return render(request, 'mydesk/dailyreport/report_detail.html', ret)

    def post(self, request):
        res = dict(result=False)
        if 'del_id' in request.POST and request.POST['del_id']:
            DailyReport.objects.filter(id=int(request.POST['del_id'])).delete()
            res['result'] = True
            return JsonResponse(res)

        if 'id' in request.POST and request.POST['id']:
            report = get_object_or_404(DailyReport, pk=int(request.POST['id']))
            report_form = EventCreateForm(request.POST, instance=report)
            if report_form.is_valid():
                report_form.save()
                res['result'] = True
        return JsonResponse(res)

templates/mydesk/dailyreport/myreport.html
{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
    <link href="{% static 'js/plugins/layer/skin/layer.css' %}" rel="stylesheet"/>
    <link href="{% static 'fullcalendar/core/main.css' %}" rel="stylesheet"/>
    <link href="{% static 'fullcalendar/daygrid/main.css' %}" rel="stylesheet"/>
    <link href="{% static 'fullcalendar/timegrid/main.css' %}" rel="stylesheet"/>
    <link href="{% static 'fullcalendar/list/main.css' %}" rel="stylesheet"/>
{#    <style>#}
{#        #calendar{#}
{#            max-width: 900px;#}
{#            margin: 0 auto;#}
{#        }#}
{#    </style>#}
{% endblock %}

{% block content %}
    <section class="content-header margin-bottom">
        <ol class="breadcrumb">
            <li><a href="">办公平台</a></li>
            <li><a href="#">我的日报</a></li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="box box-primary">
            <div class="box-body no-padding">
                <!-- THE CALENDAR -->
                <div id="calendar"></div>
            </div>
            <!-- /.box-body -->
        </div>
    </section>

    <!-- /.content -->

{% endblock %}

{% block javascripts %}
    <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
    <script src="{% static 'plugins/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'fullcalendar/core/main.min.js' %}"></script>
    <script src="{% static 'fullcalendar/interaction/main.min.js' %}"></script>
    <script src="{% static 'fullcalendar/daygrid/main.min.js' %}"></script>
    <script src="{% static 'fullcalendar/timegrid/main.min.js' %}"></script>
    <script src="{% static 'fullcalendar/list/main.min.js' %}"></script>
{#    <script src="{% static 'fullcalendar/moment/main.min.js' %}"></script>#}
    <script src="{% static 'fullcalendar/core/locales/zh-cn.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            //初始化FullCalendar
            var calendarE1 = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarE1, {
                plugins: ['interaction', 'dayGrid', 'timeGrid', 'list'],
                header: {
                   left: 'prev,next today',
                   center: 'title',
                   right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
                },
                defaultView: 'timeGridWeek', //默认视图
                locale: 'zh-cn', //中文
                navLinks: true, //可以点击日/周导航到相应的视图
                selectable: true,
                selectMirror: true,
                eventClick:function (info) {
                    var id = info.event.id;
                    layer.open({
                       type: 2,
                       title: '日程详情',
                       shadeClose: false,
                       maxmin: true,
                       area: ['800px', '460px'],
                       content: ['{% url 'mydesk:dailyreport-detail' %}' + '?id=' + id, 'no'],
                       end: function () {
                           calendar.refetchEvents();
                       }
                    });
                },
                select: function (arg) { //选中一天或者多天
                    var start = arg.startStr.slice(0, 16);
                    var end = arg.endStr.slice(0, 16);
                    layer.open({
                       type: 2,
                       title: '新建日程',
                       shadeClose: false,
                       maxmin: true,
                       area: ['800px', '460px'],
                       content: ["{% url 'mydesk:dailyreport-create' %}" + '?start=' + start + '&end=' + end, 'no'],
                       end:function () {
                           calendar.refetchEvents(); //重新加载事件内容。
                           //calendar.render();
                       }
                    });
                },
                editable: true,
                businessHours: true,
                eventLimit: true,
                events:function (info, callback) {
                    $.ajax({
                        url: '{% url 'mydesk:dailyreport-json' %}',
                        type: 'POST',
                        cache: false,
                        data: {
                            'start': info.startStr.slice(0, 19),
                            'end': info.endStr.slice(0, 19),
                            csrfmiddlewaretoken:'{{ csrf_token }}'
                        },
                        datatype: 'json',
                        success: function (data) {
                            var events = [];
                            $.each(data.data, function (i, c) {//第一个参数是index，第二个参数才是数据行
                               events.push({
                                   id: c.id,
                                   title: c.title,
                                   start: c.start,
                                   end: c.end,
                                   allDay: c.allday,
                                   color: c.type__color
                               }) ;
                            });
                            callback(events); //回调events
                        }
                    });
                },
                eventMouseEnter:function (info) { //显示tips，划过显示
                    layer.tips(info.event.title, info.el, {time:0});
                },
                eventMouseLeave:function (info) { //划出隐藏
                    var index = layer.tips();
                    layer.close(index);
                }

            });
            calendar.render();
        });

    </script>
{% endblock %}

templates/mydesk/dailyreport/report_create.html
{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-select/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block main %}
    <div class="box box-danger">
        <form class="form-horizontal" id="addForm" method="post">
            {% csrf_token %}
            <input type="hidden" name='user' value="{{ request.user.id }}"/>
            <p class="box-body">
            <fieldset>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">日程类型</label>
                    <div class="col-sm-3">
                        <select class="form-control select2" style="width:100%;" name="type">
                            <option value="">--类别--</option>
                            {% for type in types %}
                                <option value="{{ type.id }}">{{ type.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <label class="col-sm-2 control-label">日程性质</label>
                    <div class="col-sm-3">
                        <label class="control-label">
                            <input type='checkbox' class="minimal" id="allday" name="allday"/>全天
                        </label>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">参加人员</label>
                    <div class="col-sm-8">
                        <select class="form-control selectpicker" multiple="multiple" name="participants" data-placeholder="参加人员"
                                style="width: 100%;">
                            {% for p in participants %}
                                <option value="{{ p.id }}">{{ p.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">开始时间</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control pull-right form_datetime" name="start" readonly value="{{ start }}">
                    </div>
                    <label class="col-sm-2 control-label">结束时间</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control pull-right form_datetime" name="end" readonly value="{{ end }}"/>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">日程内容</label>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="title" rows="5"></textarea>
                    </div>
                </div>
                <p>
                    <small class="text-danger margin-l-5">* 上级和参加人都可以查看本条日程内容</small>
                </p>
            </fieldset>

            <div class="box-footer ">

                <div class="row span7 text-center ">
                    <button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
                    <button type="button" id="btnSave" class="btn btn-info margin-right ">保存</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'bootstrap-select/js/i18n/defaults-zh_CN.min.js' %}"></script>
    <script type="text/javascript">
        $.fn.selectpicker.Constructor.BootstrapVersion = '3.3.6';
        $("#btnSave").click(function () {
            var data = $("#addForm").serialize();
            $.ajax({
                type: $("#addForm").attr('method'),
                url: "{% url 'mydesk:dailyreport-create' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.result) {
                        layer.alert('数据保存成功！', {icon: 1}, function (index) {
                            parent.layer.closeAll(); //关闭所有弹窗
                        });
                    } else {
                        layer.alert(msg.event_create_form_errors, {icon: 5});
                        //$('errorMessage').html(msg.message)
                    }
                    return;
                }
            });
        });


        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();
        });

        /*input 时间输入选择*/
        $(".form_datetime").datetimepicker({
            language: 'zh',
            //minView: 'month',
            weekStart: 1,
            todayBtn:  1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0,
            //format: 'yyyy-mm-dd hh:ss'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
        });

        // select2
        $(function () {
            //Initialize Select2 Elements
            $(".select2").select2();
            $('.selectpicker').selectpicker({
                noneSelectedText: '请选择' //默认显示内容
            });
        });
    </script>
{% endblock %}

templates/mydesk/dailyreport/report_detail.html
{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-select/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block main %}
    <div class="box box-danger">
        <div class="box-header with-border">
            <div class="user-block">
                <img class="img-circle" src="/media/{{ report.user.image }}" alt="User Image">
                <span class="username"><a href="#">{{ report.user.name }}</a></span>
                <span class="description">创建时间: {{ report.addtime }}</span>
            </div>
            <!-- /.user-block -->
            <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-toggle="tooltip" title="Mark as read">
                    <i class="fa fa-circle-o"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <form class="form-horizontal" id="addForm" method="post">
            {% csrf_token %}
            <p class="box-body">
            <fieldset>
                <input type="hidden" name="user" value="{{ request.user.id }}">
                <input type="hidden" id='eventid' name="id" value="{{ report.id }}">
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">日程类型</label>
                    <div class="col-sm-3">
                        <select class="form-control select2" style="width:100%;" name="type">
                            <option value="{{ report.type.id }}">{{ report.type.name }}</option>
                            {% for type in types %}
                                <option value="{{ type.id }}" >{{ type.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <label class="col-sm-2 control-label">日程性质</label>
                    <div class="col-sm-3">
                        <label class="control-label">
                            <input type='checkbox' class="minimal" id="allday" name="allday" {% if report.allday %}checked{% endif %}/>全天
                        </label>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">参加人员</label>
                    <div class="col-sm-8">
                        <select class="form-control selectpicker" multiple="multiple" name="participants" data-placeholder="参加人员"
                                style="width: 100%;">
                            {% for p in user_all %}
                                <option value="{{ p.id }}" {% if p in report.participants.all %}selected="selected"{% endif %}>{{ p.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">开始时间</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control pull-right form_datetime" name="start"
                               readonly value="{{ report.start |date:'Y-m-d H:i' }}"/>
                    </div>
                    <label class="col-sm-2 control-label">结束时间</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control pull-right form_datetime" name="end" readonly
                               value="{{ report.end |date:'Y-m-d H:i' }}"/>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">日程内容</label>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="title" rows="5">{{ report.title }}</textarea>
                    </div>
                </div>
            </fieldset>

            <div class="box-footer ">

                <div class="row span7 text-center ">
                    {% ifequal request.user.id  report.user_id %}
                        <button type="button" id="btnSave" class="btn btn-info margin-right ">保存修改</button>
                        <button type="button" id="btnDel" class="btn btn-danger margin-right ">删除记录</button>
                    {% endifequal %}
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'bootstrap-select/js/i18n/defaults-zh_CN.min.js' %}"></script>
    <script type="text/javascript">

        $("#btnSave").click(function () {
            var data = $("#addForm").serialize();
            $.ajax({
                type: $("#addForm").attr('method'),
                url: "{% url 'mydesk:dailyreport-detail' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.result) {
                        layer.alert('数据保存成功！', {icon: 1}, function (index) {
                            parent.layer.closeAll();
                        });
                    } else {
                        layer.alert(msg.event_create_form_errors, {icon: 5});
                        //$('errorMessage').html(msg.message)
                    }
                    return;
                }
            });
        });


        /*点取删除数据*/
        $("#btnDel").click(function () {

            $.ajax({
                type: $("#addForm").attr('method'),
                url: "{% url 'mydesk:dailyreport-detail' %}",
                data: {'del_id': document.getElementById('eventid').value, csrfmiddlewaretoken: '{{ csrf_token }}'},
                cache: false,
                success: function (msg) {
                    if (msg.result) {
                        layer.alert('删除完成！', {icon: 1}, function (index) {
                            parent.layer.closeAll();
                        });
                    } else {
                        layer.alert(msg.event_create_form_errors, {icon: 5});
                        //$('errorMessage').html(msg.message)
                    }
                    return;
                }
            });
        });

        /*input 时间输入选择*/
        $(".form_datetime").datetimepicker({
            language: 'zh',
            //minView: 'month',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0,
            //format: 'yyyy-mm-dd'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
        });

        // select2
        $(function () {
            //Initialize Select2 Elements
            $(".select2").select2();
            $('.selectpicker').selectpicker({
                noneSelectedText: '请选择' //默认显示内容
            });
        });

    </script>

{% endblock %}

templates/mydesk/dailyreport/test.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <link rel="stylesheet" href="{% static 'dist/css/myself.css' %}">
  <link rel="stylesheet" href="{% static 'dist/css/skins/skin-blue.min.css' %}">
  <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">

    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-select/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">

  <link rel="stylesheet" href="{% static 'bootstrap-select/css/bootstrap-select.min.css' %}">





</head>
<body>


<select class="selectpicker" multiple>
  <option>Mustard</option>
  <option>Ketchup</option>
  <option>Relish</option>
   <option>Relittsh</option>
    <option>土豆</option>
</select>

<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
{#<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>#}
<script src="{% static 'bootstrap-select-1.13.9/dist/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
     <script>

        $(document).ready(function(){
          $('.selectpicker').selectpicker({
          });

          $('.selectpicker').val('Mustard');
          $('.selectpicker').selectpicker('render');
        });
     </script>
</body>