apps/system/urls.py
from django.urls import path
from .views import SystemView
from . import views_user, views_structure, views_menu, views_role


app_name = 'system'
urlpatterns = [
    path('', SystemView.as_view(), name='system'),
    path('basic/structure/', views_structure.StructureView.as_view(), name='basic-structure'),
    path('basic/structure/create/', views_structure.StructureCreateView.as_view(), name='basic-structure-create'),
    path('basic/structure/list/', views_structure.StructureListView.as_view(), name='basic-structure-list'),
    path('basic/structure/delete/', views_structure.StructureDeleteView.as_view(), name='basic-structure-delete'),
    path('basic/structure/add_user/', views_structure.Structure2UserView.as_view(), name='basic-structure-add_user'),
    path('basic/user/', views_user.UserView.as_view(), name='basic-user'),
    path('basic/user/list/', views_user.UserListView.as_view(), name='basic-user-list'),
    path('basic/user/create/', views_user.UserCreateView.as_view(), name='basic-user-create'),
    path('basic/user/detail/', views_user.UserDetailView.as_view(), name='basic-user-detail'),
    path('basic/user/update/', views_user.UserUpdateView.as_view(), name='basic-user-update'),
    path('basic/user/password_change/', views_user.PasswordChangeView.as_view(), name='basic-user-password_change'),
    path('basic/user/delete/', views_user.UserDeleteView.as_view(), name='basic-user-delete'),
    path('basic/user/enable/', views_user.UserEnableView.as_view(), name='basic-user-enable'),
    path('basic/user/disable/', views_user.UserDisableView.as_view(), name='basic-user-disable'),
    path('rbac/menu/create/', views_menu.MenuCreateView.as_view(), name='rbac-menu-create'),
    path('rbac/menu/', views_menu.MenuListView.as_view(), name='rbac-menu'),
    path('rbac/menu/update/', views_menu.MenuUpdateView.as_view(), name='rbac-menu-update'),
    path('rbac/role/', views_role.RoleView.as_view(), name='rbac-role'),
    path('rbac/role/create/', views_role.RoleCreateView.as_view(), name='rbac-role-create'),
    path('rbac/role/list/', views_role.RoleListView.as_view(), name='rbac-role-list'),
    path('rbac/role/update/', views_role.RoleUpdateView.as_view(), name='rbac-role-update'),
    path('rbac/role/delete/', views_role.RoleDeleteView.as_view(), name='rbac-role-delete'),
    path('rbac/role/role2user/', views_role.Role2UserView.as_view(), name='rbac-role-role2user'),
    path('rbac/role/role2menu/', views_role.Role2MenuView.as_view(), name='rbac-role-role2menu'),
    path('rbac/role/role2menulist/', views_role.Role2MenuListView.as_view(), name='rbac-role-role2menu_list'),


]

zbd_site/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from system.views_user import IndexView, LoginView, LogoutView
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('system/', include('system.urls', namespace='system')),
    path('sometools/', include('sometools.urls', namespace='sometools')),
    path('mydesk/', include('mydesk.urls', namespace='mydesk')),

]

if settings.DEBUG:  # 在测试环境中处理图片资源的方式
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

apps/system/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Menu(models.Model):
    """
    菜单
    """
    name = models.CharField(max_length=30, unique=True, verbose_name="菜单名")  # unique=True, 这个字段在表中必须有唯一值.
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="父菜单")
    icon = models.CharField(max_length=50, null=True, blank=True, verbose_name="图标")
    code = models.CharField(max_length=50, null=True, blank=True, verbose_name="编码")
    url = models.CharField(max_length=128, unique=True, null=True, blank=True)
    number = models.FloatField(null=True, blank=True, verbose_name='编号')

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = '菜单'
        verbose_name_plural = verbose_name
        ordering = ['number']

    @classmethod
    def get_menu_by_request_url(cls, url):
        try:
            return dict(menu=Menu.objects.get(url=url))
        except:
            return None


class Role(models.Model):
    """
    角色：用于权限绑定
    """
    name = models.CharField(max_length=32, unique=True, verbose_name="角色")
    permissions = models.ManyToManyField("Menu", blank=True, verbose_name="URL授权")
    desc = models.CharField(max_length=50, blank=True, null=True, verbose_name="描述")


class Structure(models.Model):
    """
    组织架构
    """
    type_choices = (("unit", "单位"), ("dept", "部门"))
    name = models.CharField(max_length=60, verbose_name="名称")
    type = models.CharField(max_length=20, choices=type_choices, default="dept", verbose_name="类型")
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="父类架构")

    class Meta:
        verbose_name = "组织架构"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class UserProfile(AbstractUser):
    name = models.CharField(max_length=20, default="", verbose_name="姓名")
    birthday = models.DateField(null=True, blank=True, verbose_name="出生日期")
    gender = models.CharField(max_length=10, choices=(("male", "男"), ("female", "女")),
                              default="male", verbose_name="性别")
    mobile = models.CharField(max_length=11, default="", verbose_name="手机号码")
    tel = models.CharField(max_length=11, default='', verbose_name="座机")
    image = models.ImageField(upload_to="image/%Y/%m", default="image/default.jpg",
                              max_length=100, null=True, blank=True)
    department = models.ForeignKey("Structure", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="部门")
    post = models.CharField(max_length=50, null=True, blank=True, verbose_name="职位")
    superior = models.ForeignKey("self", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="上级主管")
    roles = models.ManyToManyField("Role", verbose_name="角色", blank=True)

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

apps/system/forms.py
from django import forms
from .models import Structure, UserProfile, Role, Menu
from django.contrib.auth import get_user_model
import re


User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(required=True, error_messages={'requeired': '请填写用户名'})
    password = forms.CharField(required=True, error_messages={'requeired': '请填写密码'})


class StructureForm(forms.ModelForm):
    class Meta:
        model = Structure
        fields = ['type', 'name', 'parent']


class UserForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'birthday', 'gender', 'mobile', 'tel']


class RoleForm(forms.ModelForm):
    class Meta:
        model = Role
        fields = ['name', 'desc', 'permissions']


class UserCreateForm(forms.ModelForm):
    password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            'required': '密码不能为空',
            'min_length': '密码长度最小6位',
            'max_length': '密码长度不能超过20位',
        }
    )
    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            'required': '密码不能为空',
            'min_length': '密码长度最小6位',
            'max_length': '密码长度不能超过20位',
        }
    )

    class Meta:
        model = User
        fields = [
            'name', 'gender', 'birthday', 'username', 'mobile', 'tel',
            'department', 'post', 'superior', 'roles', 'password'
        ]
        error_messages = {
            'name': {'required': '姓名不能为空'},
            'username': {'required': '用户名不能为空'},
            'mobile': {
                'required': '手机号码不能为空',
                'min_length': '请输入有效手机号码',
                'max_length': '请输入有效手机号码',
            },
        }

        def clean(self):
            cleaned_data = super(UserCreateForm, self).clean()
            username = cleaned_data.get('username')
            mobile = cleaned_data.get('mobile', '')
            password = cleaned_data.get('password')
            confirm_password = cleaned_data.get('confirm_password')

            if User.objects.filter(username=username).count():
                raise forms.ValidationError('用户名:{}已存在'.format(username))

            if password != confirm_password:
                raise forms.ValidationError('两次密码输入不一致')

            if User.objects.filter(mobile=mobile).count():
                raise forms.ValidationError('手机号码：{}已存在'.format(mobile))

            REGEX_MOBILE = "^1[3578]\d{9}$|^147\d{8}$"
            if not re.match(REGEX_MOBILE, mobile):
                raise forms.ValidationError('手机号码：{}格式非法'.format(mobile))


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'name', 'gender', 'birthday', 'username', 'mobile', 'tel',
            'department', 'post', 'superior', 'is_active', 'roles'
        ]


class PasswordChangeForm(forms.Form):

    password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            'required': u'密码不能为空'
        })

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            'required': u'密码不能为空'
        })

    def clean(self):  # 验证通过，重写了祖先对象的clean方法进行额外验证
        cleaned_data = super(PasswordChangeForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError('两次密码输入不一致！')


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'

apps/system/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from .mixin import LoginRequiredMixin


class SystemView(LoginRequiredMixin, TemplateView):

    template_name = 'system/system_index.html'

templates/system/users/passwd_change.html
{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
{% endblock %}

{% block main %}
    <div class="box box-danger">
        <form class="form-horizontal" id="addForm" method="post">
            {% csrf_token %}
            <input type="hidden" name='id' value="{{ user.id }}"/>
            <input type="hidden" name='user' value="save"/>
            <div class="box-body">
                <fieldset>
                    <legend>
                        <h4>基本信息</h4>
                    </legend>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">姓名</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="name" type="text" readonly="readonly"
                                   value="{{ user.name }}"/>
                        </div>
                        <label class="col-sm-2 control-label">用户名</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control" name="username" readonly="readonly"
                                   value="{{ user.username }}"/>
                        </div>
                    </div>

                        <h4>密码信息</h4>
                    </legend>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">密码</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="password" type="password" value=""/>
                        </div>
                        <label class="col-sm-2 control-label">确认密码</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="confirm_password" type="password" value=""/>
                        </div>
                    </div>

                </fieldset>

            </div>
            <div class="box-footer ">
                <div class="row span7 text-center ">
                    <button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
                    <button type="button" id="btnSave" class="btn btn-info margin-right ">确定</button>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/combo-select/jquery.combo.select.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
    <script type="text/javascript">

        $("#btnSave").click(function () {
            var data = $("#addForm").serialize();
            $.ajax({
                type: $("#addForm").attr('method'),  //根据form的method属性值确定type=post or get
                url: "{% url 'system:basic-user-password_change' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.status == 'success') {
                        layer.alert('密码修改成功！', {icon: 1}, function (index) {
                            parent.layer.closeAll();
                        });
                    } else if (msg.status == 'fail') {
                        layer.alert(msg.password_change_form_errors, {icon: 5});
                        //$('errorMessage').html(msg.message)
                    }
                    return;
                }
            });
        });


        /*点取消刷新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();

        })


    </script>

{% endblock %}

templates/system/users/user_create.html
{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
{% endblock %}
{% block main %}
    <div class="box box-danger">
        <form class="form-horizontal" id="addForm" method="post">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ user.id }}"/>
            <input type="hidden" name="user" value="save"/>
            <div class="box-body">
                <fieldset>
                    <legend>
                        <h4>基本信息</h4>
                    </legend>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">姓名</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="name" type="text" value=""/>
                        </div>
                        <label class="col-sm-2 control-label">性别</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="gender">
                                <option value="male">男</option>
                                <option value="female">女</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">生日</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control pull-right form_datetime" name="birthday"/>
                        </div>
                        <label class="col-sm-2 control-label">用户名</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control" name="username"/>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">状态</label>
                        <div class="col-sm-6">
                            <label class="control-label">
                                <input type='radio' class="minimal" name="is_active" value="True" checked>启用
                            </label>
                            <label class="control-label">
                                <input type="radio" class="minimal" name="is_active" value="False">禁用
                            </label>
                        </div>
                    </div>
                <legend>
                    <h4>密码信息</h4>
                </legend>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">密码</label>
                    <div class="col-sm-3">
                        <input class="form-control" name="password" type="password" value=""/>
                    </div>
                    <label class="col-sm-2 control-label">确认密码</label>
                    <div class="col-sm-3">
                        <input class="form-control" name="confirm_password" type="password" value=""/>
                    </div>
                </div>
                <legend>
                    <h4>联系信息</h4>
                </legend>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">手机</label>
                    <div class="col-sm-3">
                        <input class="form-control" name="mobile" type="text"/>
                    </div>
                    <label class="col-sm-2 control-label">座机</label>
                    <div class="col-sm-3">
                        <input class="form-control" name="tel" type="text"/>
                    </div>
                </div>
                <legend>
                    <h4>职务信息</h4>
                </legend>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">部门</label>
                    <div class="col-sm-3">
                        <select class="form-control select2" style="width: 100%;" name="department">
                            <option value="">--部门--</option>
                            {% for structure in structrues %}
                                <option value="{{ structure.id }}">{{ structure.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">岗位</label>
                    <div class="col-sm-3">
                        <input class="form-control" name="post" type="text"/>
                    </div>
                    <label class="col-sm-2 control-label">上级</label>
                    <div class="col-sm-3">
                        <select class="form-control select2" style="width:100%;" name="superior">
                            <option value="">--上级--</option>
                            {% for user in users %}
                                <option value="{{ user.id }}">{{ user.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">所属角色组</label>
                    <div class="col-sm-6">
                        {% for role in roles %}
                            <label class="control-label">
                                <input type="checkbox" class="minimal" name="roles" value="{{ role.id }}"
                                {% if role in user_roles %}checked{% endif %}>{{ role.name }}
                            </label>
                        {% endfor %}
                    </div>
                </div>
                </fieldset>
            </div>
            <div class="box-footer">
                <div class="row span7 text-center">
                    <button type="button" id="btnCancel" class="btn btn-default margin-right">重置</button>
                    <button type="button" id="btnSave" class="btn btn-default margin-right">保存</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
    <script>
        $('#btnSave').click(function () {
            var data = $('#addForm').serialize();
            $.ajax({
                type: $('#addForm').attr('method'),
                url: "{% url 'system:basic-user-create' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.status == 'success'){
                        layer.alert('用户添加成功！',{icon: 1}, function (index) {
                            parent.layer.closeAll(); //关闭所有弹窗
                        });
                    }else if (msg.status == 'fail'){
                        layer.alert(msg.user_create_form_errors, {icon: 5});
                    }
                    return;
                }
            });
        });
        //点取消刷新页面
        $('#btnCancel').click(function () {
            window.location.reload();
        });
        //input 时间输入选择
        $(".form_datetime").datetimepicker({
            language: 'zh',
            minView: 'month', //选择范围只到日期，不选择时分
            autoclose: 1,
            todayHighlight: 1,
            forceParse: 0,
            showMeridian: 1,
            format: 'yyyy-mm-dd'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
        });
        $(function () {
            //初始化 select2的元素
            $('.select2').select2();
        })
    </script>
{% endblock %}

templates/system/users/user_detail.html
{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
{% endblock %}
{% block main %}
    <div class="box box-danger">
        <form class="form-horizontal" id='addForm' method="post">
            {% csrf_token %}
            <input type='hidden' name="id" value="{{ user.id }}"/>
            <input type="hidden" name="user" value="save"/>
            <div class="box-body">
                <fieldset>
                    <legend>
                        <h4>基本信息</h4>
                    </legend>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">姓名</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="name" type="text" value="{{ user.name }}"/>
                        </div>
                        <label class="col-sm-2 control-label">性别</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="gender">
                                <option value={{ user.gender }}> {{ user.get_gender_display }} </option>
                                <option value="male">男</option>
                                <option value="female">女</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">生日</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control pull-right form_datetime" name="birthday"
                                   value="{{ user.birthday|date:"Y-m-d" }}"/>
                        </div>
                        <label class="col-sm-2 control-label">用户名</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control" name="username" readonly="readonly"
                                   value="{{ user.username }}"/>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">状态</label>
                        <div class="col-sm-6">
                            <label class="control-label">
                                <input type="radio" class="minimal" name="is_active" value="True"
                                       {% ifequal user.is_active True %}checked{% endifequal %}>启用
                            </label>
                            <label class="control-label">
                                <input type="radio" class="minimal" name="is_active" value="False"
                                       {% ifequal user.is_active False %}checked{% endifequal %}>禁用
                            </label>
                        </div>
                    </div>
                    <legend>
                        <h4 clase="">联系信息</h4>
                    </legend>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">手机</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="mobile" readonly="readonly" type="text"
                                   value="{{ user.mobile }}"/>
                        </div>
                        <label class="col-sm-2 control-label">座机</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="tel" type="text" value="{{ user.tel }}"/>
                        </div>
                    </div>
                    <legend>
                        <h4>职务信息</h4>
                    </legend>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">部门</label>
                        <div class="col-sm-3">
                            <select class="form-control select2" style="width:100%;" name="department">
                                <option value="{{ user.department.id }}">{{ user.department.name|default:"--部门--" }}</option>
                                {% for structure in structures %}
                                    <option value="{{ structure.id }}">{{ structure.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">岗位</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="post" type="text"
                                   value="{{ user.post|default_if_none:"" }}"/>
                        </div>
                        <label class="col-sm-2 control-label">上级</label>
                        <div class="col-sm-3">
                            <select class="form-control select2" style="width:100%;" name="superior">
                                <option value="{{ user.superior.id }}">{{ user.superior.name|default:"--上级--" }}</option>
                                {% for user in users %}
                                    <option value="{{ user.id }}">{{ user.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">所属角色组</label>
                        <div class="col-sm-6">
                            {% for role in roles %}
                                <label class="control-label">
                                    <input type="checkbox" class="minimal" name="roles" value="{{ role.id }}"
                                           {% if role in user_roles %}checked{% endif %}>
                                    {{ role.name }}
                                </label>
                            {% endfor %}
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="box-footer text-center">
                <button type="button" id="btnCancel" class="btn btn-default margin-right">重置</button>
                <button type="button" id="btnSave" class="btn btn-default margin-right">保存</button>
            </div>
        </form>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
    <script>
        //点击取消刷新新页面
        $('#btnCancel').click(function () {
            window.location.reload()
        })
        // input 时间输入选择
        $('.form_datetime').datetimepicker({
            language: 'zh',
            minView: 'month',
            autoclose: 1,
            todayHighlight: 1,
            forceParse: 0,
            showMeridian: 1,
            format: 'yyyy-mm-dd'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
        });

        $(function () {
            $('.select2').select2();
        });
        $('#btnSave').click(function () {
            var data = $('#addForm').serialize();
            $.ajax({
                type: $('#addForm').attr('method'),
                url: '/system/basic/user/update/',
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.status == 'success'){
                        layer.alert('数据保存成功!',{icon:1}, function(index){
                            parent.layer.closeAll(); //关闭所有弹窗
                        });
                    }else if (msg.status == 'fail'){
                        layer.alert('数据保存失败！',{icon:5});
                    }
                    return;
                }
            });
        });
    </script>
{% endblock %}